// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNtMtLv7ZIQWtbit_L46tk88ba_BKmTM0',
    appId: '1:36762927212:web:0b8a619d4a6130bd7d1849',
    messagingSenderId: '36762927212',
    projectId: 'car-rent-app-5cbdd',
    authDomain: 'car-rent-app-5cbdd.firebaseapp.com',
    storageBucket: 'car-rent-app-5cbdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1prP4Uc1rKdscDbWqM5t2LyAZT-ZsWt8',
    appId: '1:36762927212:android:fd4d25208a783b827d1849',
    messagingSenderId: '36762927212',
    projectId: 'car-rent-app-5cbdd',
    storageBucket: 'car-rent-app-5cbdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-gQu7MTOsYeKedRHMplxJ7dejIF7phTM',
    appId: '1:36762927212:ios:9fe3a7ee1ca08c7f7d1849',
    messagingSenderId: '36762927212',
    projectId: 'car-rent-app-5cbdd',
    storageBucket: 'car-rent-app-5cbdd.appspot.com',
    iosBundleId: 'com.example.carRentApp',
  );
}
